### ISSUE TITLE
Entrega Trabajo Práctico N° 1

### ISSUE THREAD

**Issue by mecsafonso** [mecsafonso/2020_K2031-K2002_Grupo_1#1]
Solicito corrección del trabajo práctico: @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados, muy buen trabajo

Nota 9

Está todo muy claro. Excepto como buscan la columna del caracter. Pude comprender lo que hicieron. Armaron una cadena con todos los caracteres y luego buscar ahí.

Pero, quizás es más fácil algo así

caracter >= '1' && caracter <= '7'

caracter == '8' || caracter == '9'

caracter >= 'a' && caracter <= 'f'

caracter >= 'A' && caracter <= 'F'

Se los muestro como una alternativa, total son caracteres consecutivos en el código ASCII.

Lo que ustedes plantean sería bueno si los caracteres que debemos evaluar no están ordenados en el código ASCII. De hecho sería una posible solución, pero para este caso no es necesario

FELICITACIONES ! =D
A seguir así.

**Comment by mecsafonso** [comment]
Gracias por la corrección profesor @santiagoferreiros ,
Ya hemos realizado y commiteado las modificaciones que usted nos sugirió.
Saludos!

**Comment by mecsafonso** [comment]
(reopen)
Gracias por la corrección profesor @santiagoferreiros ,
Ya hemos realizado y commiteado las modificaciones que usted nos sugirió.
Saludos!

**Comment by santiagoferreiros** [comment]
Excelente ! Ya les he modificado la nota !
