### ISSUE TITLE
Entrega del Trabajo Práctico N° 2

### ISSUE THREAD

**Issue by SolVarisco** [mecsafonso/2020_K2031-K2002_Grupo_1#2]
Solicito corrección del trabajo práctico @santiagoferreiros 
En la carpeta de entrega hay dos conjuntos de archivos. El TP2.c, y su respectivo .exe, es el trabajo final que tenemos que entregar. Mientras que el archivo TP2_VersionExtendida.c, y su respectivo .exe, es una versión del trabajo que muestra como se va modificando la pila a medida que se analizan las expresiones.

**Comment by santiagoferreiros** [comment]
Estimados,

IMPECABLE.
Excelente trabajo. Sin observaciones. Muy prolijo todo.
Felicitaciones para ustedes =)

Nota: 10

@SolVarisco @mecsafonso @lautaropetronacci @erangelortega
