### ISSUE TITLE
Entrega del Trabajo Práctico N° 3

### ISSUE THREAD

**Issue by mecsafonso** [mecsafonso/2020_K2031-K2002_Grupo_1#3]
Buenas tardes profe @santiagoferreiros =D,
Solicito corrección del trabajo práctico. 
Saludos!

**Comment by santiagoferreiros** [comment]
IMPECABLE!

Nota: 10

Luego me gustaría que me comenten un poco sobre el trabajo, como lo llevaron adelante, está muy bien.

FELICITACIONES =)
